### PR TITLE
adds arg for path creation

### LINKED ISSUE #88: Output doesn't make intermediary directories
For example, if the dir `bar` doesn't exist, this fails:

    lesscpy foo.less /bar/foo.css

Where this will work:

    lessc foo.less /bar/foo.css

This is biting me for a django static compiler issue, and would be glad to add the functionality if it can be rolled in.

### PR DESCRIPTION
**Pull request by LegoStormtroopr**
This will fix #88 
I need to add a test for it.

### CODE REVIEW

**Comment by saschpe** [comment]
So the travis-ci part is one commit, the others should be squashed.

**Comment by LegoStormtroopr** [comment]
I think you can squash commits via the squash merge option. Sorry, but I'm not sure how I'd go about doing it from the command line. https://github.com/blog/2141-squash-your-commits

**Comment by saschpe** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by LegoStormtroopr** [comment]
Cheers, I'll give it a shot.

**Comment by LegoStormtroopr** [comment]
Hey! I did it! Thanks for the help @saschpe :)

**Comment by saschpe** [comment]
You're welcome. Thanks for the contribution!

**Pull request merged**
